FROM gwbexec1_2:latest
USER root
# ensure rwx permissions everywhere in ~
RUN chmod 777 -R /home/ubuntu
#
COPY entry.sh /bin/entry.sh
RUN  chmod a+x /bin/entry.sh
# execute as user ubuntu, using default Cyverse mount point as workdir
USER ubuntu
# add directory for iRODS iCommands to user profile as JSON, see entry.sh
RUN mkdir /home/ubuntu/.irods 
RUN chown ubuntu:ubuntu  /home/ubuntu/.irods
WORKDIR /home/ubuntu/data-store/
ENTRYPOINT ["bash", "/bin/entry.sh"]